### ISSUE TITLE
Long Pressing Causes Crashes

### ISSUE THREAD

**Issue by MJonesDev** [MJonesDev/Aperture-Gallery-Android#1]
This crash is most likely due to using a newer version of MediaCab without updating the code. This can also be due to using a new version of Aidan Follestad's DragSelector library. 
Logcat As follows: 

8-31548/com.marlonjones.aperture E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.marlonjones.aperture, PID: 31548
                                                                          java.lang.NoSuchFieldError: No field abc_ic_ab_back_mtrl_am_alpha of type I in class Lcom/afollestad/materialcab/R$drawable; or its superclasses (declaration of 'com.afollestad.materialcab.R$drawable' appears in /data/app/com.marlonjones.aperture-1/base.apk:classes19.dex)
                                                                              at com.afollestad.materialcab.MaterialCab.reset(MaterialCab.java:88)
                                                                              at com.afollestad.materialcab.MaterialCab.<init>(MaterialCab.java:67)
                                                                              at com.marlonjones.projectevo.cab.MediaCab.start(MediaCab.java:80)
                                                                              at com.marlonjones.projectevo.fragments.MediaFragment.onClick(MediaFragment.java:161)
                                                                              at com.marlonjones.projectevo.adapters.MediaAdapter.onLongClick(MediaAdapter.java:274)

**Comment by MJonesDev** [comment]
This has been fixed by updating to Material-Cab 0.1.12
